node{
    stage(’Checkout’){
        checkoutscm
}
    stage(’Build’){
        docker.image(’trion/ng−cli’).inside{
            sh’npminstall’
            sh’ngbuild−−progressfalse−−prod−−aot’
            sh’tar−cvzfdist.tar.gz−−strip−components=1dist’
        }
        archive’dist.tar.gz’
    }

    stage(’Test’){
        docker.image(’trion/ng−cli−karma’).inside{
        sh’ngtest−−progressfalse−−watchfalse’
        }
    }
}
